/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.util.Map;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Fabrizio Ortega
 */
public class ChartPanel extends javax.swing.JPanel {
    DefaultCategoryDataset data;
    /**
     * Creates new form ChartPanel
     */
    public ChartPanel() {
        initComponents();
        data = new DefaultCategoryDataset();
        JFreeChart chart = ChartFactory.createLineChart(
            "",
            "","",
            data,
            PlotOrientation.VERTICAL,
            true,true,false);
       
        chart.getPlot().setBackgroundPaint(Color.white);
        

	org.jfree.chart.ChartPanel panel = new org.jfree.chart.ChartPanel(chart); 
	panel.setPreferredSize( new java.awt.Dimension(1212, 585));
        this.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1212, 585));
        setPreferredSize(new java.awt.Dimension(1212, 585));
    }// </editor-fold>//GEN-END:initComponents

    int count = 0;
	public void updateStats(double max, double avg, Map<String, Double>others) {
		data.addValue(max, "Max", (Integer)count);
		data.addValue(avg, "Avg", (Integer)count);
		for(var e:others.entrySet()) data.addValue(e.getValue(), e.getKey(), (Integer)count);
		count++;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
